dist: xenial

language: java

jdk:
  - oraclejdk8

notifications:
  email:
    recipients:
      - olaf.danne@brockmann-consult.de
      - marco.peters@brockmann-consult.de
      - tonio.fincke@brockmann-consult.de
    on_success: change # default: change
    on_failure: always # default: always
